global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/alerts.yml

scrape_configs:
  - job_name: "auth_microservice"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "api:8000"
  - job_name: "redis_exporter"
    static_configs:
      - targets:
          - "redis-exporter:9121"
  - job_name: "rabbitmq_exporter"
    static_configs:
      - targets:
          - "rabbitmq-exporter:9419"
